# Generated by Django 6.0 on 2025-12-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('blocks_per_bag', models.IntegerField(help_text='Expected blocks from 1 bag of cement')),
                ('sand_ratio', models.DecimalField(decimal_places=2, help_text='Tons of sand per batch', max_digits=5)),
                ('batch_size', models.IntegerField(default=1350, help_text='Batch size for sand ratio')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CEMENT', 'Cement (Bags)'), ('SHARP_SAND', 'Sharp Sand (Tons)'), ('BLACK_SAND', 'Black Sand (Tons)'), ('DIESEL', 'Diesel (Liters)'), ('STONE_DUST', 'Stone Dust (Tons)')], max_length=20, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Current cost per unit', max_digits=10)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_name', models.CharField(default='Jafan Standard Block Ind', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
