# Generated by Django 6.0 on 2025-12-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_blocktype_material_paymentaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Production Rates', max_length=50)),
                ('sand_cost', models.DecimalField(decimal_places=2, default=330000, help_text='Cost for 30 tons of sand', max_digits=12)),
                ('black_sand_cost', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('water_base_cost', models.DecimalField(decimal_places=2, default=28800, max_digits=12)),
                ('operator_rate', models.DecimalField(decimal_places=2, default=35.0, help_text='Pay per block', max_digits=10)),
                ('loader_rate', models.DecimalField(decimal_places=2, default=9.0, help_text='Pay per block', max_digits=10)),
                ('logistics_rate', models.DecimalField(decimal_places=2, default=65.0, help_text='Logistics cost per block', max_digits=10)),
                ('diesel_power_cost', models.DecimalField(decimal_places=2, default=18000, max_digits=12)),
                ('miscellaneous_cost', models.DecimalField(decimal_places=2, default=45000, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Rules',
                'verbose_name_plural': 'Business Rules',
            },
        ),
    ]
