# Generated by Django 6.0 on 2025-12-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_businessrules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessrules',
            name='loader_rate',
        ),
        migrations.RemoveField(
            model_name='businessrules',
            name='operator_rate',
        ),
        migrations.AddField(
            model_name='blocktype',
            name='loader_rate',
            field=models.DecimalField(decimal_places=2, default=9.0, help_text='Loader pay per block', max_digits=10),
        ),
        migrations.AddField(
            model_name='blocktype',
            name='operator_rate',
            field=models.DecimalField(decimal_places=2, default=35.0, help_text='Operator pay per block', max_digits=10),
        ),
        migrations.AddField(
            model_name='blocktype',
            name='stacking_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Stacking pay per block', max_digits=10),
        ),
    ]
