# Generated by Django 6.0 on 2025-12-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_remove_businessrules_loader_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessrules',
            name='logistics_rate',
        ),
        migrations.AddField(
            model_name='blocktype',
            name='logistics_rate',
            field=models.DecimalField(decimal_places=2, default=65.0, help_text='Logistics cost per block', max_digits=10),
        ),
    ]
