# Generated by Django 6.0 on 2025-12-21 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_remove_businessrules_logistics_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('office_address', models.TextField(blank=True, help_text='Main office or billing address', null=True)),
                ('customer_type', models.CharField(choices=[('ENGINEER', 'Engineer'), ('DEVELOPER', 'Developer'), ('CONTRACTOR', 'Contractor'), ('INDIVIDUAL', 'Individual'), ('OTHER', 'Other')], default='INDIVIDUAL', max_length=20)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Pre-paid deposit balance', max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('OPERATOR', 'Machine Operator'), ('LOADER', 'Loader'), ('DRIVER', 'Driver'), ('MIXER', 'Mixer'), ('STACKER', 'Stacker'), ('CARRIER', 'Carrier'), ('MANAGER', 'Manager'), ('SALES', 'Sales Staff'), ('SECURITY', 'Security'), ('OTHER', 'Other')], max_length=20)),
                ('team', models.CharField(blank=True, help_text='e.g., Team A, Machine 1', max_length=50, null=True)),
                ('pay_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Negative = owes company (loan), Positive = company owes them', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='loader_rate',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='logistics_rate',
            field=models.DecimalField(decimal_places=2, default=65.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='operator_rate',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='stacking_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='businessrules',
            name='sand_cost',
            field=models.DecimalField(decimal_places=2, default=330000, max_digits=12),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., GRA Phase 2, UniAgric Site', max_length=100)),
                ('address', models.TextField(help_text='Full delivery address for driver')),
                ('contact_person', models.CharField(blank=True, help_text='On-site contact if different', max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_outside_town', models.BooleanField(default=False, help_text='Attracts outside town surcharge?')),
                ('blocks_owed', models.IntegerField(default=0, help_text='Paid but undelivered blocks for this site')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='erp.customer')),
            ],
            options={
                'ordering': ['customer', 'name'],
            },
        ),
    ]
