# Generated by Django 6.0 on 2025-12-23 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_team_machine_alter_employee_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('supply_type', models.CharField(choices=[('CEMENT', 'Cement'), ('SAND', 'Sand'), ('FUEL', 'Fuel/Diesel'), ('MAINTENANCE', 'Maintenance/Repairs'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current quantity available', max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Alert when stock falls below this', max_digits=10),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Truck A, Tipper 1', max_length=50, unique=True)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_DELIVERY', 'On Delivery'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=20)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol')], default='DIESEL', max_length=10)),
                ('fuel_capacity', models.DecimalField(decimal_places=2, default=0.0, help_text='Tank capacity (Liters)', max_digits=5)),
                ('benchmark_fuel', models.DecimalField(decimal_places=2, default=30.0, help_text='Benchmark liters per cycle', max_digits=5)),
                ('expected_trips', models.IntegerField(default=8, help_text='Expected trips per benchmark fuel')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trucks', to='erp.employee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Amount purchased', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.material')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.paymentaccount')),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.vendor')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
