# Generated by Django 6.0 on 2025-12-23 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_vendor_material_current_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocktype',
            name='current_stock',
            field=models.IntegerField(default=0, help_text='Blocks ready for sale'),
        ),
        migrations.AddField(
            model_name='blocktype',
            name='low_stock_threshold',
            field=models.IntegerField(default=500, help_text='Alert when stock falls below this'),
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_produced', models.PositiveIntegerField(help_text='Number of blocks produced')),
                ('breakages', models.PositiveIntegerField(default=0, help_text='Blocks broken during production')),
                ('cement_used', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('sand_used', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.blocktype')),
                ('machine', models.ForeignKey(limit_choices_to={'machine_type': 'BLOCK'}, on_delete=django.db.models.deletion.PROTECT, to='erp.machine')),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.team')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
