# Generated by Django 6.0 on 2025-12-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_blocktype_current_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionlog',
            name='sand_used',
        ),
        migrations.AddField(
            model_name='productionlog',
            name='black_sand_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tons of black sand used', max_digits=10),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='sharp_sand_used',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto-calculated from recipe', max_digits=10),
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='sand_ratio',
            field=models.DecimalField(decimal_places=2, help_text='Tons of sharp sand per batch', max_digits=5),
        ),
        migrations.AlterField(
            model_name='procurementlog',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Amount purchased (bags, tons, liters)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='procurementlog',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, help_text='Total amount paid', max_digits=12),
        ),
        migrations.AlterField(
            model_name='procurementlog',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto-calculated: total_cost / quantity', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='cement_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bags of cement used', max_digits=10),
        ),
    ]
