# Generated by Django 6.0 on 2025-12-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_remove_productionlog_sand_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='supply_type',
            field=models.CharField(choices=[('CEMENT', 'Cement'), ('SHARP_SAND', 'Sharp Sand'), ('BLACK_SAND', 'Black Sand'), ('FUEL', 'Fuel/Diesel'), ('MAINTENANCE', 'Maintenance/Repairs'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
