# Generated by Django 6.0 on 2025-12-23 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_salesorder_salesorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='truck',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='quantity_supplied',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Amount already delivered via Supply Logs'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Positive = Customer has credit, Negative = Customer owes', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Quote)'), ('CONFIRMED', 'Confirmed (Active)'), ('COMPLETED', 'Fully Supplied'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Total quantity ordered'),
        ),
        migrations.CreateModel(
            name='SupplyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_loaded', models.PositiveIntegerField(help_text='Blocks loaded onto truck')),
                ('quantity_delivered', models.PositiveIntegerField(help_text='Blocks actually delivered (after breakages)')),
                ('breakages', models.PositiveIntegerField(default=0, help_text='Blocks broken during loading/transit')),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.employee')),
                ('order_item', models.ForeignKey(help_text='Which block type from the order?', on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='erp.salesorderitem')),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(help_text='Select confirmed order to supply', limit_choices_to={'status': 'CONFIRMED'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='erp.salesorder')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.truck')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
