# Generated by Django 6.0 on 2025-12-23 22:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_remove_salesorder_truck_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='balance_due',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='is_outside_town',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='agreed_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Agreed price per block', max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='quantity_requested',
            field=models.PositiveIntegerField(default=0, help_text='Quantity customer wants'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplylog',
            name='block_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='erp.blocktype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplylog',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='erp.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplylog',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='erp.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplylog',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='supplylog',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Price per block for this supply', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Positive = Credit (we owe blocks), Negative = Debit (they owe money)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='erp.customer'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='outside_town_surcharge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.site'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Quote)'), ('APPROVED', 'Approved (Ready to Supply)'), ('IN_PROGRESS', 'In Progress (Partially Supplied)'), ('COMPLETED', 'Completed (Fully Supplied)'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='quantity_supplied',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Quantity already delivered'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.employee'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to specific order item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='erp.salesorderitem'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='quantity_delivered',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to a sales order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='erp.salesorder'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount received', max_digits=12)),
                ('method', models.CharField(choices=[('TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('POS', 'POS Terminal'), ('CHEQUE', 'Cheque')], default='TRANSFER', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Bank Ref / Teller No / Receipt No', max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='erp.customer')),
                ('payment_account', models.ForeignKey(blank=True, help_text='Which account received the money?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.paymentaccount')),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
