# Generated by Django 6.0 on 2025-12-25 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_remove_salesorder_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplylog',
            name='delivery_type',
            field=models.CharField(choices=[('DELIVERED', 'Company Delivery'), ('SELF_PICKUP', 'Customer Self-Pickup')], default='DELIVERED', max_length=20),
        ),
        migrations.AddField(
            model_name='supplylog',
            name='logistics_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount for self-pickup', max_digits=10),
        ),
        migrations.AddField(
            model_name='supplylog',
            name='pickup_authorized_by',
            field=models.CharField(blank=True, help_text='Name/ID of person who picked up (for self-pickup)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Required for company delivery', limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.employee'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='quantity_loaded',
            field=models.PositiveIntegerField(help_text='Blocks loaded onto truck or picked up'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='truck',
            field=models.ForeignKey(blank=True, help_text='Required for company delivery', null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.truck'),
        ),
    ]
