# Generated by Django 6.0 on 2025-12-26 08:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_supplylog_delivery_type_supplylog_logistics_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(help_text='Reason for refund')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(help_text='Must be Admin or GM', limit_choices_to={'role__in': ['ADMIN', 'GM']}, on_delete=django.db.models.deletion.PROTECT, related_name='approved_refunds', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='erp.customer')),
                ('payment_account', models.ForeignKey(help_text='Bank account paying the refund', on_delete=django.db.models.deletion.PROTECT, to='erp.paymentaccount')),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity_returned', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('GOOD', 'Good/Reusable (Add to Stock)'), ('DAMAGED', 'Damaged/Condemned (Do not add to Stock)')], default='GOOD', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price to credit back (usually original buying price)', max_digits=10)),
                ('restocking_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Deduction for transport/handling', max_digits=10)),
                ('credit_value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('reason', models.TextField(help_text='Reason for return')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(help_text='Must be Admin or GM', limit_choices_to={'role__in': ['ADMIN', 'GM']}, on_delete=django.db.models.deletion.PROTECT, related_name='approved_returns', to=settings.AUTH_USER_MODEL)),
                ('block_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.blocktype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='erp.customer')),
                ('original_supply', models.ForeignKey(blank=True, help_text='Optional: Link to original supply', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.supplylog')),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_returns', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.site')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
