# Generated by Django 6.0 on 2025-12-27 12:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_cashrefund_returnlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(help_text='Brief description of expense', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt_number', models.CharField(blank=True, help_text='Receipt or invoice number', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_auto_synced', models.BooleanField(default=False, editable=False, help_text='True if auto-created from Procurement')),
                ('requires_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'GM']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, help_text='Employee if salary/advance/allowance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.employee')),
                ('machine', models.ForeignKey(blank=True, help_text='Machine if equipment-related expense', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.machine')),
                ('payment_account', models.ForeignKey(blank=True, help_text='Account used for payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.paymentaccount')),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(blank=True, help_text='Truck if vehicle-related expense', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.truck')),
                ('vendor', models.ForeignKey(blank=True, help_text='Vendor if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.vendor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='erp.expensecategory')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='procurementlog',
            name='expense_entry',
            field=models.OneToOneField(blank=True, editable=False, help_text='Auto-created expense entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_source', to='erp.expense'),
        ),
    ]
