# Generated by Django 6.0 on 2025-12-29 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_seed_expense_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocktype',
            name='is_half_block',
            field=models.BooleanField(default=False, help_text='Is this a half/broken block type?'),
        ),
        migrations.AddField(
            model_name='returnlog',
            name='restock_as',
            field=models.ForeignKey(blank=True, help_text='Optional: If returned block is now different type (e.g., Whole → Half), select Half Block type here', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restocked_returns', to='erp.blocktype'),
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='blocks_per_bag',
            field=models.IntegerField(default=0, help_text='Expected blocks from 1 bag of cement (0 for non-produced items)'),
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='sand_ratio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tons of sharp sand per batch', max_digits=5),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='block_type',
            field=models.ForeignKey(help_text='The original block type that was sold', on_delete=django.db.models.deletion.PROTECT, to='erp.blocktype'),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='condition',
            field=models.CharField(choices=[('GOOD', 'Good/Reusable (Full Block)'), ('HALF', 'Broken but Reusable (Half Block)'), ('DAMAGED', 'Damaged/Condemned (No Restock)')], default='GOOD', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='original_supply',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to original supply for audit trail', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.supplylog'),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price to credit back per block (₦0 if no refund for breakages)', max_digits=10),
        ),
    ]
