# Generated by Django 6.0 on 2025-12-30 08:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_blocktype_is_half_block_returnlog_restock_as_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnlog',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Return Log', 'verbose_name_plural': 'Return Logs'},
        ),
        migrations.AddField(
            model_name='returnlog',
            name='credit_customer',
            field=models.BooleanField(default=False, help_text='⚠️ Check ONLY if customer should receive account credit (e.g., customer-initiated refund). Leave UNCHECKED for excess blocks from delivery or breakage conversions.'),
        ),
        migrations.AddField(
            model_name='returnlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='approved_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['ADMIN', 'GM']}, on_delete=django.db.models.deletion.PROTECT, related_name='approved_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='block_type',
            field=models.ForeignKey(help_text='The block type that was originally supplied', on_delete=django.db.models.deletion.PROTECT, to='erp.blocktype'),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='credit_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Actual credit applied to customer account', max_digits=12),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='original_supply',
            field=models.ForeignKey(blank=True, help_text='Link to original supply (optional, for traceability)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.supplylog'),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='reason',
            field=models.TextField(help_text="Reason for return (e.g., 'Excess from delivery', 'Customer rejected')"),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='restock_as',
            field=models.ForeignKey(blank=True, help_text='If returned block is now different type (e.g., Whole → Half), select target type here. Leave empty to restock as original.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restocked_returns', to='erp.blocktype'),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='restocking_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Fee deducted from credit (only used if 'Credit Customer' is checked)", max_digits=10),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Credit per block (only used if 'Credit Customer' is checked)", max_digits=10),
        ),
    ]
