# Generated by Django 6.0 on 2026-01-01 01:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_alter_returnlog_options_returnlog_credit_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Sales Order', 'verbose_name_plural': 'Sales Orders'},
        ),
        migrations.AlterModelOptions(
            name='salesorderitem',
            options={'verbose_name': 'Sales Order Item', 'verbose_name_plural': 'Sales Order Items'},
        ),
        migrations.AlterModelOptions(
            name='supplylog',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Supply Log', 'verbose_name_plural': 'Supply Logs'},
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='outside_town_surcharge',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_per_block',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount deducted PER BLOCK (e.g., ₦20 bulk discount)', max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='surcharge_per_block',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount added PER BLOCK (e.g., ₦50 for outside town delivery)', max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Proforma validity date (auto-set to 14 days if empty)', null=True),
        ),
        migrations.AddField(
            model_name='supplylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='erp.customer'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='discount_reason',
            field=models.CharField(blank=True, default=1, help_text='Reason for discount (if any)', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='notes',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='erp.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PARTIAL', 'Partially Supplied'), ('COMPLETED', 'Fully Supplied'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='agreed_price',
            field=models.DecimalField(decimal_places=2, help_text='Auto-calculated: Block price + surcharge - discount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='quantity_requested',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='quantity_supplied',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='block_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='erp.blocktype'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='breakages',
            field=models.PositiveIntegerField(default=0, help_text='Blocks broken during delivery'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='erp.employee'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='logistics_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount for delivery issues (breakages, delays)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='Link to specific order item (auto-populates unit_price)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='erp.salesorderitem'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='pickup_authorized_by',
            field=models.CharField(blank=True, default=1, help_text='Name of person who authorized pickup (for self-pickup)', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='quantity_delivered',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-calculated: loaded - breakages'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='quantity_loaded',
            field=models.PositiveIntegerField(help_text='Blocks loaded onto truck'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_supplies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='remark',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='erp.salesorder'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.site'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='erp.truck'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-populated from Sales Order or Block Type price', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='BreakageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity_broken', models.PositiveIntegerField(help_text='Number of blocks damaged')),
                ('reason', models.CharField(choices=[('STACKING', 'Broken during stacking'), ('RAIN', 'Rain/weather damage'), ('ACCIDENT', 'Site accident'), ('HANDLING', 'Improper handling'), ('PRODUCTION', 'Production defect'), ('TRANSPORT', 'Internal transport damage'), ('OTHER', 'Other')], default='HANDLING', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about the breakage incident')),
                ('convert_to_half', models.BooleanField(default=False, help_text='Check if broken blocks can be salvaged as half blocks')),
                ('quantity_salvaged', models.PositiveIntegerField(default=0, help_text='Number of half blocks salvaged (usually 2x broken if salvageable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(help_text='Manager who approved this breakage write-off', limit_choices_to={'role__in': ['ADMIN', 'GM']}, on_delete=django.db.models.deletion.PROTECT, related_name='approved_breakages', to=settings.AUTH_USER_MODEL)),
                ('block_type', models.ForeignKey(help_text='The full block type that was damaged', on_delete=django.db.models.deletion.PROTECT, related_name='breakages', to='erp.blocktype')),
                ('half_block_type', models.ForeignKey(blank=True, help_text='Select the half block type to add to stock (only if converting)', limit_choices_to={'is_half_block': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salvaged_from_breakages', to='erp.blocktype')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_breakages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Breakage Log',
                'verbose_name_plural': 'Breakage Logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
