# Generated by Django 6.0 on 2026-01-01 09:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_alter_salesorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnlog',
            name='credit_customer',
            field=models.BooleanField(default=False, help_text='⚠️ Check ONLY if customer should receive account credit.'),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='reason',
            field=models.TextField(help_text='Reason for return'),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='restock_as',
            field=models.ForeignKey(blank=True, help_text='If returned block is now different type (e.g., Whole → Half), select target type here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restocked_returns', to='erp.blocktype'),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='restocking_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee deducted from credit', max_digits=10),
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('destination_type', models.CharField(choices=[('TRUCK', 'Truck / Logistics'), ('MACHINE', 'Generator / Machine')], default='TRUCK', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Liters dispensed', max_digits=10)),
                ('engine_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Run hours (for Generators)', max_digits=10, null=True)),
                ('cost_per_liter', models.DecimalField(decimal_places=2, editable=False, help_text='Cost at time of dispensing', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispensed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to='erp.machine')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to='erp.truck')),
            ],
            options={
                'verbose_name': 'Fuel Log',
                'verbose_name_plural': 'Fuel Logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
