# Generated by Django 6.0 on 2026-01-01 16:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_alter_returnlog_credit_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplylog',
            name='logistics_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Income attributed to Jafan Transport (Rate + Surcharge)', max_digits=12),
        ),
    ]
