# Generated by Django 6.0 on 2026-01-01 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_supplylog_logistics_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementlog',
            name='delivery_truck',
            field=models.ForeignKey(blank=True, help_text='Select the Truck that did the work (Credits revenue to this truck)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_deliveries', to='erp.truck'),
        ),
        migrations.AddField(
            model_name='procurementlog',
            name='is_internal_haulage',
            field=models.BooleanField(default=False, help_text='Check if this was delivered by Jafan Transport (e.g. Tipper/Tanker)'),
        ),
    ]
