# Generated by Django 6.0 on 2026-01-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_procurementlog_delivery_truck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(choices=[('CEMENT', 'Cement (Bags)'), ('SHARP_SAND', 'Sharp Sand (Tons)'), ('BLACK_SAND', 'Black Sand (Tons)'), ('DIESEL', 'Diesel (Liters)'), ('STONE_DUST', 'Stone Dust (Tons)'), ('WATER', 'Water (Liters)')], max_length=20, unique=True),
        ),
    ]
