# Generated by Django 6.0 on 2026-01-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_alter_material_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_inventory_tracked',
            field=models.BooleanField(default=True, help_text='Uncheck for items (like Water) where you track Cost but not Quantity.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
