# Generated by Django 6.0 on 2026-01-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_material_is_inventory_tracked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='truck_type',
            field=models.CharField(choices=[('BLOCK', 'Block Carrier'), ('TIPPER', 'Tipper'), ('TANKER', 'Tanker'), ('OTHER', 'Other/Utility')], default='BLOCK', help_text='Categorize the vehicle function', max_length=20),
        ),
    ]
