# Generated by Django 6.0 on 2026-01-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_truck_truck_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Check this if the vendor is a Jafan Department (e.g., Jafan Transport)'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='supply_type',
            field=models.CharField(choices=[('CEMENT', 'Cement'), ('SHARP_SAND', 'Sharp Sand'), ('BLACK_SAND', 'Black Sand'), ('FUEL', 'Fuel/Diesel'), ('MAINTENANCE', 'Maintenance/Repairs'), ('TRANSPORT', 'Transport/Haulage'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
