# Generated by Django 6.0 on 2026-01-02 18:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_vendor_is_internal_alter_vendor_supply_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('target_type', models.CharField(choices=[('TRUCK', 'Truck'), ('MACHINE', 'Generator/Machine')], default='TRUCK', max_length=10)),
                ('service_type', models.CharField(choices=[('ROUTINE', 'Routine Service (Oil/Filters)'), ('REPAIR', 'Mechanical Repair'), ('TIRES', 'Tire Replacement'), ('ELECTRICAL', 'Electrical Works'), ('BODY', 'Body Work/Welding')], max_length=20)),
                ('description', models.TextField(help_text='Details of work done (e.g. Changed fan belt)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_service_date', models.DateField(blank=True, help_text='Reminder for next service', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='erp.machine')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='erp.truck')),
                ('vendor', models.ForeignKey(limit_choices_to={'supply_type__in': ['MAINTENANCE', 'OTHER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.vendor')),
            ],
            options={
                'verbose_name': 'Maintenance Log',
                'verbose_name_plural': 'Maintenance Logs',
                'ordering': ['-date'],
            },
        ),
    ]
