# Generated by Django 6.0 on 2026-01-05 11:32

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_maintenancelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentaccount',
            options={'ordering': ['business_unit', 'bank_name']},
        ),
        migrations.AddField(
            model_name='expense',
            name='business_unit',
            field=models.CharField(choices=[('BLOCK', 'Jafan Block Industry'), ('TRANSPORT', 'Jafan Transport')], default='BLOCK', help_text='Which business incurred this expense?', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Driver who incurred expense (for transport)', limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_expenses', to='erp.employee'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Uncheck if this is a credit purchase (pay vendor later)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date when payment was made (if different from expense date)', null=True),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Driver who received fuel', limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_received', to='erp.employee'),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='fuel_station',
            field=models.CharField(blank=True, help_text='Where fuel was purchased', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='fuel_type',
            field=models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('ENGINE_OIL', 'Engine Oil')], default='DIESEL', max_length=15),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Bank Transfer'), ('POS', 'POS')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='expense_entry',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_source', to='erp.expense'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Bank Transfer'), ('POS', 'POS')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='recorded_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='account_type',
            field=models.CharField(choices=[('BANK', 'Bank Account'), ('MOBILE', 'Mobile Money (Moniepoint, OPay)'), ('POS', 'POS Terminal'), ('CASH', 'Cash at Hand')], default='BANK', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='business_unit',
            field=models.CharField(choices=[('BLOCK', 'Jafan Block Industry'), ('TRANSPORT', 'Jafan Transport')], default='BLOCK', help_text='Which business owns this account?', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-calculated from transactions', max_digits=14),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='last_audit_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Physical count at last audit', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='last_audit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='last_audit_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Starting balance when system went live', max_digits=14),
        ),
        migrations.AddField(
            model_name='procurementlog',
            name='haulage_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee paid to Jafan Transport for delivery (if internal haulage)', max_digits=12),
        ),
        migrations.AddField(
            model_name='procurementlog',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Uncheck if vendor gave on credit (pay later)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Positive = We owe them, Negative = They owe us', max_digits=12),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='cost_per_liter',
            field=models.DecimalField(decimal_places=2, help_text='Cost per liter', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='destination_type',
            field=models.CharField(choices=[('TRUCK', 'Truck / Logistics'), ('MACHINE', 'Generator / Machine'), ('ASSET', 'Transport Asset (Bike/Car)')], default='TRUCK', max_length=10),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='service_type',
            field=models.CharField(choices=[('ROUTINE', 'Routine Service (Oil/Filters)'), ('REPAIR', 'Mechanical Repair'), ('TIRES', 'Tire Replacement/Repair'), ('ELECTRICAL', 'Electrical Works'), ('BODY', 'Body Work/Welding'), ('SPRING', 'Spring Work'), ('CLUTCH', 'Clutch Work')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='target_type',
            field=models.CharField(choices=[('TRUCK', 'Truck'), ('MACHINE', 'Generator/Machine'), ('ASSET', 'Transport Asset (Bike/Car)')], default='TRUCK', max_length=10),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'supply_type__in': ['MAINTENANCE', 'OTHER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.vendor'),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='account_name',
            field=models.CharField(default='GC Okoli Enterprises', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='bank_name',
            field=models.CharField(help_text="Bank name or 'Cash', 'POS', etc.", max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('GM', 'General Manager'), ('SUPPLY', 'Supply Manager'), ('SITE', 'Site Manager'), ('SALES', 'Sales Representative'), ('TRANSPORT', 'Transport Manager')], default='SALES', max_length=10),
        ),
        migrations.CreateModel(
            name='AccountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, help_text='Bank transfer reference', max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_transport_settlement', models.BooleanField(default=False, help_text='Check if this is Block Industry paying Transport (Monday settlement)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense_entry', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_source', to='erp.expense')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='erp.paymentaccount')),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='erp.paymentaccount')),
            ],
            options={
                'verbose_name': 'Account Transfer',
                'verbose_name_plural': 'Account Transfers',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('charge_type', models.CharField(choices=[('TRANSFER_FEE', 'Transfer Fee'), ('SMS_ALERT', 'SMS Alert Charge'), ('MAINTENANCE', 'Account Maintenance'), ('STAMP_DUTY', 'Stamp Duty'), ('ATM', 'ATM Charges'), ('POS_CHARGE', 'POS Charge'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_charges', to='erp.paymentaccount')),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Charge',
                'verbose_name_plural': 'Bank Charges',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Transport Manager Bike', max_length=50, unique=True)),
                ('asset_type', models.CharField(choices=[('BIKE', 'Motorcycle'), ('CAR', 'Car'), ('TRICYCLE', 'Tricycle/Keke'), ('OTHER', 'Other')], default='BIKE', max_length=20)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel')], default='PETROL', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Employee who uses this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.employee')),
            ],
            options={
                'verbose_name': 'Transport Asset',
                'verbose_name_plural': 'Transport Assets',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='transport_asset',
            field=models.ForeignKey(blank=True, help_text='Transport asset (bike/car) if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='erp.transportasset'),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='transport_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to='erp.transportasset'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='transport_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='erp.transportasset'),
        ),
        migrations.CreateModel(
            name='TransportRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('job_type', models.CharField(choices=[('WATER', 'Water Delivery'), ('SAND_HAUL', 'Sand/Gravel Hauling'), ('EXTERNAL', 'External Haulage'), ('RENTAL', 'Equipment Rental'), ('OTHER', 'Other')], default='WATER', max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('trips', models.PositiveIntegerField(default=1, help_text='Number of trips (for water delivery)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=True, help_text='External customers pay cash')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Bank Transfer'), ('POS', 'POS')], default='CASH', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_jobs', to='erp.employee')),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_logs', to='erp.truck')),
            ],
            options={
                'verbose_name': 'Transport Revenue',
                'verbose_name_plural': 'Transport Revenue',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
