# Generated by Django 6.0 on 2026-01-06 08:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_alter_paymentaccount_options_expense_business_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('system_balance_at_close', models.DecimalField(decimal_places=2, help_text='What the software says you should have.', max_digits=12)),
                ('physical_cash_count', models.DecimalField(decimal_places=2, help_text='What you actually counted in the safe.', max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, editable=False, help_text='Physical - System. Negative means shortage.', max_digits=12)),
                ('status', models.CharField(choices=[('BALANCED', '✅ Balanced'), ('SHORT', 'wq Shortage (Money Missing)'), ('EXCESS', '⚠️ Excess (Too Much Money)')], editable=False, max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Explain any difference here.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(limit_choices_to={'account_type': 'CASH'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_closes', to='erp.paymentaccount')),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Cash Close',
                'verbose_name_plural': 'Daily Cash Closes',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
