# Generated by Django 6.0 on 2026-01-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0031_dailycashclose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycashclose',
            name='status',
            field=models.CharField(choices=[('BALANCED', '✅ Balanced'), ('SHORT', '❌ Shortage (Money Missing)'), ('EXCESS', '⚠️ Excess (Too Much Money)')], editable=False, max_length=20),
        ),
    ]
