# Generated by Django 6.0 on 2026-01-07 06:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0032_alter_dailycashclose_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transportasset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={},
        ),
        migrations.AddField(
            model_name='blocktype',
            name='weighted_average_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Auto-calculated WAC based on production costs', max_digits=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum allowed debt (positive value). Example: 500,000 means they can owe up to 500k.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='Optional: Link this payment to a specific order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='erp.salesorder'),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Cost per block (Materials + Labor + Overhead)', max_digits=10),
        ),
        migrations.AddField(
            model_name='supplylog',
            name='quantity_returned',
            field=models.PositiveIntegerField(default=0, help_text='Blocks rejected on site and returned immediately (Added back to stock)'),
        ),
        migrations.AlterField(
            model_name='accounttransfer',
            name='is_transport_settlement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accounttransfer',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='blocks_per_bag',
            field=models.IntegerField(default=0, help_text='Expected blocks from 1 bag of cement'),
        ),
        migrations.AlterField(
            model_name='breakagelog',
            name='approved_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['ADMIN', 'GM']}, on_delete=django.db.models.deletion.PROTECT, related_name='approved_breakages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='breakagelog',
            name='block_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breakages', to='erp.blocktype'),
        ),
        migrations.AlterField(
            model_name='breakagelog',
            name='convert_to_half',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='breakagelog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='breakagelog',
            name='half_block_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_half_block': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salvaged_from_breakages', to='erp.blocktype'),
        ),
        migrations.AlterField(
            model_name='breakagelog',
            name='quantity_broken',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='breakagelog',
            name='quantity_salvaged',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cashrefund',
            name='approved_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['ADMIN', 'GM']}, on_delete=django.db.models.deletion.PROTECT, related_name='approved_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashrefund',
            name='payment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.paymentaccount'),
        ),
        migrations.AlterField(
            model_name='cashrefund',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailycashclose',
            name='difference',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailycashclose',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailycashclose',
            name='physical_cash_count',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailycashclose',
            name='system_balance_at_close',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='business_unit',
            field=models.CharField(choices=[('BLOCK', 'Jafan Block Industry'), ('TRANSPORT', 'Jafan Transport')], default='BLOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_expenses', to='erp.employee'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.employee'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_auto_synced',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.machine'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.paymentaccount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='transport_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='erp.transportasset'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.truck'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.vendor'),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='cost_per_liter',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_received', to='erp.employee'),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='engine_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='fuel_station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='next_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.paymentaccount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='business_unit',
            field=models.CharField(choices=[('BLOCK', 'Jafan Block Industry'), ('TRANSPORT', 'Jafan Transport')], default='BLOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='last_audit_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='procurementlog',
            name='delivery_truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_deliveries', to='erp.truck'),
        ),
        migrations.AlterField(
            model_name='procurementlog',
            name='expense_entry',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_source', to='erp.expense'),
        ),
        migrations.AlterField(
            model_name='procurementlog',
            name='haulage_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='procurementlog',
            name='is_internal_haulage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='procurementlog',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='procurementlog',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Amount purchased', max_digits=10),
        ),
        migrations.AlterField(
            model_name='procurementlog',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='procurementlog',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='black_sand_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='cement_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='sharp_sand_used',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='block_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.blocktype'),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='credit_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='credit_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='original_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.supplylog'),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='restock_as',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restocked_returns', to='erp.blocktype'),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='restocking_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='discount_per_block',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='surcharge_per_block',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='agreed_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='blocks_owed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='site',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='is_outside_town',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(help_text='e.g., GRA Phase 2', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='breakages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='logistics_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='logistics_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='erp.salesorderitem'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='pickup_authorized_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='quantity_delivered',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='quantity_loaded',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transportasset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.employee'),
        ),
        migrations.AlterField(
            model_name='transportasset',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transportrevenue',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.employee'),
        ),
        migrations.AlterField(
            model_name='transportrevenue',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transportrevenue',
            name='trips',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='truck',
            name='benchmark_fuel',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='truck',
            name='expected_trips',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='truck',
            name='fuel_capacity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='truck',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_type',
            field=models.CharField(choices=[('BLOCK', 'Block Carrier'), ('TIPPER', 'Tipper'), ('TANKER', 'Tanker'), ('OTHER', 'Other/Utility')], default='BLOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
