# Generated by Django 6.0 on 2026-01-08 14:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0033_alter_employee_options_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttransfer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bankcharge',
            options={},
        ),
        migrations.AlterModelOptions(
            name='breakagelog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dailycashclose',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='maintenancelog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='procurementlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='returnlog',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='salesorderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transportrevenue',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='accounttransfer',
            name='expense_entry',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.expense'),
        ),
        migrations.AlterField(
            model_name='bankcharge',
            name='charge_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='batch_size',
            field=models.IntegerField(default=1350),
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='blocks_per_bag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='current_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='is_half_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='low_stock_threshold',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='sand_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='weighted_average_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='breakagelog',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_breakages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='breakagelog',
            name='half_block_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salvaged_from_breakages', to='erp.blocktype'),
        ),
        migrations.AlterField(
            model_name='breakagelog',
            name='reason',
            field=models.CharField(choices=[('STACKING', 'Stacking'), ('HANDLING', 'Handling')], default='HANDLING', max_length=20),
        ),
        migrations.AlterField(
            model_name='cashrefund',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(default='INDIVIDUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailycashclose',
            name='status',
            field=models.CharField(choices=[('BALANCED', 'Balanced'), ('SHORT', 'Shortage'), ('EXCESS', 'Excess')], editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pay_type',
            field=models.CharField(default='WEEKLY', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.team'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='business_unit',
            field=models.CharField(default='BLOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.expensecategory'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_expenses', to='erp.employee'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='recorded_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='transport_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.transportasset'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='destination_type',
            field=models.CharField(choices=[('TRUCK', 'Truck'), ('MACHINE', 'Generator'), ('ASSET', 'Asset')], default='TRUCK', max_length=10),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_received', to='erp.employee'),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='fuel_type',
            field=models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('ENGINE_OIL', 'Oil')], default='DIESEL', max_length=15),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='payment_method',
            field=models.CharField(default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.team'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(default='OPERATIONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='expense_entry',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.expense'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='payment_method',
            field=models.CharField(default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='service_type',
            field=models.CharField(choices=[('ROUTINE', 'Routine'), ('REPAIR', 'Repair')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='target_type',
            field=models.CharField(choices=[('TRUCK', 'Truck'), ('MACHINE', 'Machine'), ('ASSET', 'Asset')], default='TRUCK', max_length=10),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.vendor'),
        ),
        migrations.AlterField(
            model_name='material',
            name='is_inventory_tracked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('POS', 'POS'), ('CHEQUE', 'Cheque')], default='TRANSFER', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='erp.salesorder'),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='account_type',
            field=models.CharField(choices=[('BANK', 'Bank Account'), ('MOBILE', 'Mobile Money'), ('POS', 'POS Terminal'), ('CASH', 'Cash at Hand')], default='BANK', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='bank_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='procurementlog',
            name='delivery_truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.truck'),
        ),
        migrations.AlterField(
            model_name='procurementlog',
            name='expense_entry',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.expense'),
        ),
        migrations.AlterField(
            model_name='procurementlog',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='breakages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='quantity_produced',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='condition',
            field=models.CharField(choices=[('GOOD', 'Good'), ('HALF', 'Broken (Half)'), ('DAMAGED', 'Damaged')], default='GOOD', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='quantity_returned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transportasset',
            name='asset_type',
            field=models.CharField(default='BIKE', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportasset',
            name='fuel_type',
            field=models.CharField(default='PETROL', max_length=10),
        ),
        migrations.AlterField(
            model_name='transportasset',
            name='plate_number',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transportrevenue',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_jobs', to='erp.employee'),
        ),
        migrations.AlterField(
            model_name='transportrevenue',
            name='job_type',
            field=models.CharField(default='WATER', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportrevenue',
            name='payment_method',
            field=models.CharField(default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='truck',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.employee'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='fuel_type',
            field=models.CharField(default='DIESEL', max_length=10),
        ),
        migrations.AlterField(
            model_name='truck',
            name='plate_number',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_type',
            field=models.CharField(default='BLOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='supply_type',
            field=models.CharField(default='OTHER', max_length=20),
        ),
    ]
