# Generated by Django 6.0 on 2026-01-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0035_vendorpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlog',
            name='black_sand_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manual entry: Tons used', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='cement_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manual entry: Bags used', max_digits=10),
        ),
    ]
