# Generated by Django 6.0 on 2026-01-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0036_alter_productionlog_black_sand_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='team_pay',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text="Operator's specific cut", max_digits=12),
        ),
    ]
