# Generated by Django 6.0 on 2026-01-09 22:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0037_productionlog_team_pay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procurementlog',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='procurementlog',
            name='expense_entry',
        ),
        migrations.AddField(
            model_name='supplylog',
            name='cost_of_goods_sold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Frozen: quantity_delivered × WAC at time of sale', max_digits=12),
        ),
        migrations.AddField(
            model_name='supplylog',
            name='gross_profit_on_sale',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='total_value - cost_of_goods_sold', max_digits=12),
        ),
    ]
