# Generated by Django 6.0 on 2026-01-12 18:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0038_alter_procurementlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_type', models.CharField(choices=[('TEAM_PAY', 'Team Production Pay'), ('STACKING', 'Stacking Payment'), ('LOADING', 'Loading Payment'), ('OTHER', 'Other Production Labor')], default='TEAM_PAY', max_length=20)),
                ('period_start', models.DateField(help_text='Start of work period (e.g., Monday)')),
                ('period_end', models.DateField(help_text='End of work period (e.g., Saturday)')),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Auto-calculated from ProductionLog (for reference)', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Actual amount paid', max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, help_text='Select employee for individual payments', null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.employee')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.paymentaccount')),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Select team for production pay', null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.team')),
            ],
            options={
                'verbose_name': 'Team Payment',
                'verbose_name_plural': 'Team Payments',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
