# Generated by Django 6.0 on 2026-01-13 17:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0039_teampayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampayment',
            name='calculated_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Auto-calculated from ProductionLog (for team pay only)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='teampayment',
            name='description',
            field=models.TextField(blank=True, help_text="E.g., 'Daily loading for 500 blocks' or 'Stacking at Customer X site'"),
        ),
        migrations.AlterField(
            model_name='teampayment',
            name='period_end',
            field=models.DateField(blank=True, help_text='End of work period (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='teampayment',
            name='period_start',
            field=models.DateField(blank=True, help_text='Start of work period (optional)', null=True),
        ),
    ]
