# Generated by Django 6.0 on 2026-02-12 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0040_alter_teampayment_calculated_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.paymentaccount'),
        ),
    ]
