# Generated by Django 6.0 on 2026-02-13 02:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0041_maintenancelog_payment_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='discount_per_block',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='discount_reason',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='discount_per_block',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='erp.paymentaccount'),
            preserve_default=False,
        ),
    ]
