# Generated by Django 6.0 on 2026-02-14 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0042_remove_salesorder_discount_per_block_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandVehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sand Vehicle Type',
                'verbose_name_plural': 'Sand Vehicle Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SandSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of vehicles')),
                ('unit_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('customer_name', models.CharField(blank=True, help_text='Optional - for walk-in customers', max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.paymentaccount')),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='erp.sandvehicletype')),
            ],
            options={
                'verbose_name': 'Sand Sale',
                'verbose_name_plural': 'Sand Sales',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
