# Generated by Django 6.0 on 2026-02-27 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0044_debtor_loan_loanrepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrevenue',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Required if paid', limit_choices_to={'business_unit': 'TRANSPORT'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.paymentaccount'),
        ),
    ]
