# Generated by Django 6.0 on 2026-02-27 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0045_transportrevenue_payment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellog',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Required if paid', null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.paymentaccount'),
        ),
    ]
