# Generated by Django 6.0 on 2026-02-28 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0046_fuellog_is_paid_fuellog_payment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to Django user account for login access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrator'), ('TRANSPORT', 'Transport'), ('SALES', 'Sales'), ('PRODUCTION', 'Production'), ('ACCOUNTS', 'Accounts')], max_length=20),
        ),
    ]
