# Generated by Django 6.0 on 2026-03-04 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0047_employee_user_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakagelog',
            name='is_auto_created',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='breakagelog',
            name='supply_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakage_logs', to='erp.supplylog'),
        ),
        migrations.AlterField(
            model_name='breakagelog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_breakages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='breakagelog',
            name='reason',
            field=models.CharField(choices=[('STACKING', 'Stacking'), ('HANDLING', 'Handling'), ('LOADING_OFFLOADING', 'Loading/Offloading')], default='HANDLING', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrator'), ('MANAGER', 'General Manager'), ('OPERATIONS', 'Operations Manager'), ('SITE_MANAGER', 'Site Manager'), ('SALES', 'Sales Assistant'), ('TRANSPORT', 'Transport Officer')], max_length=20),
        ),
    ]
