# Generated by Django 6.0 on 2026-03-11 04:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0048_breakagelog_is_auto_created_breakagelog_supply_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrator'), ('MANAGER', 'General Manager'), ('OPERATIONS', 'Operations Manager'), ('SITE_MANAGER', 'Site Manager'), ('SALES', 'Sales Assistant'), ('TRANSPORT', 'Transport Officer'), ('DRIVER', 'Driver'), ('OPERATOR', 'Machine Operator'), ('CARRIER', 'Loader/Carrier'), ('SECURITY', 'Security'), ('GENERAL', 'General Worker')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuickSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Bank Transfer'), ('POS', 'POS')], default='CASH', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Transfer reference or POS receipt', max_length=100)),
                ('buyer_name', models.CharField(blank=True, help_text="Optional - buyer's name", max_length=100)),
                ('buyer_phone', models.CharField(blank=True, help_text="Optional - buyer's phone", max_length=24)),
                ('pickup_authorized_by', models.CharField(blank=True, max_length=100)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.blocktype')),
                ('payment_account', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='erp.paymentaccount')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_sales_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quick Sale',
                'verbose_name_plural': 'Quick Sales',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
