# Generated by Django 6.0 on 2026-03-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0049_alter_customer_phone_alter_employee_role_quicksale'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicksale',
            name='logistics_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount for self-pickup (no delivery)', max_digits=10),
        ),
    ]
