# Generated by Django 6.0 on 2026-03-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0050_quicksale_logistics_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicksale',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Auto-filled from block type selling price', max_digits=10),
        ),
    ]
