# Generated by Django 6.0 on 2026-03-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0051_alter_quicksale_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicksale',
            name='logistics_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount per block for self-pickup (e.g., ₦50/block)', max_digits=10),
        ),
    ]
