# Generated by Django 6.0 on 2026-03-19 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0052_alter_quicksale_logistics_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicksale',
            name='secondary_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quick_sales_secondary', to='erp.paymentaccount', verbose_name='Secondary Account'),
        ),
        migrations.AddField(
            model_name='quicksale',
            name='secondary_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid via secondary method (leave 0 if single payment)', max_digits=12),
        ),
        migrations.AddField(
            model_name='quicksale',
            name='secondary_method',
            field=models.CharField(blank=True, choices=[('', '---------'), ('CASH', 'Cash'), ('TRANSFER', 'Bank Transfer'), ('POS', 'POS')], max_length=20, verbose_name='Secondary Method'),
        ),
        migrations.AddField(
            model_name='quicksale',
            name='secondary_reference',
            field=models.CharField(blank=True, help_text='Secondary payment reference', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='business_unit',
            field=models.CharField(choices=[('BLOCK', 'Jafan Block Industry'), ('TRANSPORT', 'Jafan Transport'), ('SAND', 'JAFAN SAND')], default='BLOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='quicksale',
            name='payment_account',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='quick_sales_primary', to='erp.paymentaccount', verbose_name='Primary Account'),
        ),
        migrations.AlterField(
            model_name='quicksale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Bank Transfer'), ('POS', 'POS')], default='CASH', max_length=20, verbose_name='Primary Method'),
        ),
    ]
