# Generated by Django 6.0 on 2026-03-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0053_quicksale_secondary_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['pk']},
        ),
        migrations.RenameField(
            model_name='salesorderitem',
            old_name='discount_per_block',
            new_name='discount_value',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='discount_type',
            field=models.CharField(choices=[('PER_BLOCK', 'Per Block'), ('BULK', 'Bulk (Fixed Amount)')], default='PER_BLOCK', max_length=10),
        ),
    ]
