# Generated by Django 6.0 on 2026-03-26 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0054_alter_salesorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicksale',
            name='block_type',
            field=models.ForeignKey(blank=True, help_text='Legacy field - use Items for new sales', null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.blocktype'),
        ),
        migrations.AlterField(
            model_name='quicksale',
            name='logistics_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy field - use Items for new sales', max_digits=10),
        ),
        migrations.AlterField(
            model_name='quicksale',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Legacy field - use Items for new sales', null=True),
        ),
        migrations.AlterField(
            model_name='quicksale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quicksale',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Legacy field - auto-filled from block type', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='QuickSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, editable=False, help_text='Auto-filled from block type selling price', max_digits=10)),
                ('logistics_discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount per block for self-pickup', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('block_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.blocktype')),
                ('quick_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.quicksale')),
            ],
            options={
                'verbose_name': 'Quick Sale Item',
                'verbose_name_plural': 'Quick Sale Items',
            },
        ),
    ]
