# Generated by Django 6.0 on 2026-03-26 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0055_add_quicksaleitem_multiitem_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplylog',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.site'),
        ),
    ]
