# Generated by Django 6.0 on 2026-04-01 05:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0056_make_supplylog_site_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterCompanyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'C&C Frozen Food → Block Industry'", max_length=100, unique=True)),
                ('creditor_company', models.CharField(default='C&C Frozen Food', help_text='Company providing the cash (lender)', max_length=100)),
                ('debtor_company', models.CharField(default='Jafan Standard Block Industry', help_text='Company receiving the cash (borrower)', max_length=100)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current amount owed. Positive = debtor owes creditor.', max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inter-Company Account',
                'verbose_name_plural': 'Inter-Company Accounts',
            },
        ),
        migrations.CreateModel(
            name='OffenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('severity', models.CharField(choices=[('A', 'Category A - Minor (Start at Step 1)'), ('B', 'Category B - Moderate (Start at Step 2)'), ('C', 'Category C - Serious (Start at Step 3/4)'), ('D', 'Category D - Terminable (Immediate)')], max_length=1)),
                ('description', models.TextField(blank=True, help_text='Description and escalation path per the constitution')),
                ('default_fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default fine amount (₦) if applicable. 0 = no fine.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Offence Category',
                'verbose_name_plural': 'Offence Categories',
                'ordering': ['severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WelfareFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month this record covers', unique=True)),
                ('total_fines_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('spent_description', models.TextField(blank=True, help_text='What was purchased (drinks, food, etc.)')),
                ('spent_date', models.DateField(blank=True, null=True)),
                ('is_disbursed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Welfare Fund',
                'verbose_name_plural': 'Welfare Fund',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('action_taken', models.CharField(choices=[('VERBAL', 'Verbal Warning'), ('WRITTEN', 'Written Warning'), ('FINAL', 'Final Warning'), ('FINE', 'Fine'), ('SUSPENSION', 'Suspension'), ('TERMINATION', 'Termination')], max_length=15)),
                ('offence_description', models.TextField(help_text='Specific details of what happened')),
                ('suspension_days', models.PositiveIntegerField(default=0, help_text='Number of days suspended (0 if not a suspension)')),
                ('suspension_start', models.DateField(blank=True, null=True)),
                ('suspension_end', models.DateField(blank=True, null=True)),
                ('pay_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount deducted from pay (₦)', max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired (Clean Record Reset)'), ('SERVED', 'Served'), ('APPEALED', 'Under Appeal')], default='ACTIVE', max_length=10)),
                ('witness', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinary_records', to='erp.employee')),
                ('issued_by', models.ForeignKey(help_text='Foreman, GM, or MD who issued the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_actions_issued', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('offence_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='erp.offencecategory')),
            ],
            options={
                'verbose_name': 'Disciplinary Record',
                'verbose_name_plural': 'Disciplinary Records',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('fine_type', models.CharField(choices=[('VERBAL_ABUSE', 'Verbal Abuse (₦1,500)'), ('THREAT', 'Threats & Intimidation (₦2,000)'), ('FIGHTING', 'Physical Fighting (₦5,000)'), ('ADMIN_THREAT', 'Threat Against Admin Staff (₦5,000)'), ('OTHER', 'Other Fine')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incident_description', models.TextField(help_text="What happened — both parties' accounts")),
                ('is_deducted', models.BooleanField(default=False, help_text="Has this fine been deducted from the worker's pay?")),
                ('deduction_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disciplinary_record', models.OneToOneField(blank=True, help_text='Link to the disciplinary record if auto-created', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fine_record', to='erp.disciplinaryrecord')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='erp.employee')),
                ('issued_by', models.ForeignKey(help_text='General Manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_issued', to=settings.AUTH_USER_MODEL)),
                ('other_party', models.ForeignKey(blank=True, help_text='The other worker involved (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_as_other_party', to='erp.employee')),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fine (Section 4)',
                'verbose_name_plural': 'Fines (Section 4)',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('repayment_method', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Bank Transfer'), ('OFFSET', 'Offset Against Revenue'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_account', models.ForeignKey(help_text='Block Industry account that the repayment was made from', on_delete=django.db.models.deletion.PROTECT, related_name='intercompany_repayments', to='erp.paymentaccount')),
                ('inter_company_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='erp.intercompanyaccount')),
            ],
            options={
                'verbose_name': 'Cash Repayment (to C&C)',
                'verbose_name_plural': 'Cash Repayments (to C&C)',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('purpose', models.CharField(choices=[('OPS', 'General Operations'), ('TRANSPORTER', 'Transporter Advance'), ('MATERIALS', 'Raw Materials Purchase'), ('SALARY', 'Salary/Wages'), ('EMERGENCY', 'Emergency/Urgent'), ('OTHER', 'Other')], default='OPS', max_length=20)),
                ('purpose_detail', models.CharField(blank=True, help_text="Specific reason, e.g. 'Advance for Driver Emeka - Dangote trip'", max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, help_text='Link to transporter/driver if this is a driver advance', limit_choices_to={'role__in': ['DRIVER', 'TRANSPORT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercompany_advances', to='erp.employee')),
                ('receiving_account', models.ForeignKey(help_text='Block Industry account that received the cash', on_delete=django.db.models.deletion.PROTECT, related_name='intercompany_collections', to='erp.paymentaccount')),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inter_company_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='erp.intercompanyaccount')),
            ],
            options={
                'verbose_name': 'Cash Collection (from C&C)',
                'verbose_name_plural': 'Cash Collections (from C&C)',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]