# Generated by Django 6.0 on 2026-04-01 05:53

from django.db import migrations
from decimal import Decimal


def seed_offence_categories(apps, schema_editor):
    OffenceCategory = apps.get_model('erp', 'OffenceCategory')

    categories = [
        # Category A - Minor Offences (Section 3.2)
        {'name': 'Lateness (up to 15 minutes)', 'severity': 'A',
         'description': '1st = Verbal Warning. 2nd = Written Warning. 3rd in same month = 1-day pay deduction.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Failure to wear appropriate work attire', 'severity': 'A',
         'description': 'Progressive discipline from Step 1.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Leaving workstation without permission', 'severity': 'A',
         'description': 'Progressive discipline from Step 1.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Failure to clean workstation at end of day', 'severity': 'A',
         'description': 'Progressive discipline from Step 1.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Personal phone use during production hours', 'severity': 'A',
         'description': 'Progressive discipline from Step 1.',
         'default_fine_amount': Decimal('0')},

        # Category B - Moderate Offences (Section 3.3)
        {'name': 'Unexcused absence', 'severity': 'B',
         'description': '1st = Written Warning + loss of weekly attendance bonus. 2nd = Final Warning. 3rd = Suspension.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Producing blocks with wrong mix ratio (carelessness)', 'severity': 'B',
         'description': 'Written Warning. Repeat = Final Warning + investigation.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Failing to report machine faults or damaged equipment', 'severity': 'B',
         'description': 'Progressive discipline from Step 2.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Insubordination', 'severity': 'B',
         'description': 'Refusal to follow reasonable work instruction. Progressive discipline from Step 2.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Conducting personal business or side jobs on company time', 'severity': 'B',
         'description': 'Written Warning. 2nd offence = Final Warning + pay deduction.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Reporting to work impaired', 'severity': 'B',
         'description': 'Sent home without pay. 2nd incident within 3 months = Written Warning. 3rd = Suspension.',
         'default_fine_amount': Decimal('0')},

        # Category C - Serious Offences (Section 3.4)
        {'name': 'Deliberately reducing cement to inflate production', 'severity': 'C',
         'description': 'Immediate suspension + investigation. If confirmed: termination.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Hiding broken blocks or falsifying production records', 'severity': 'C',
         'description': 'Immediate suspension + investigation. If confirmed: termination.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Repeated poor quality output after warnings', 'severity': 'C',
         'description': 'Final Warning. Next occurrence = termination.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Abandoning post', 'severity': 'C',
         'description': 'Security leaving gate, driver leaving vehicle. Suspension 1-3 days. Repeat = termination.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Unauthorised removal of company property from premises', 'severity': 'C',
         'description': 'Suspension + investigation. May escalate to termination.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Gross insubordination or verbal abuse of a supervisor', 'severity': 'C',
         'description': 'Final Warning + fine. Repeat = suspension.',
         'default_fine_amount': Decimal('1500')},
        {'name': 'Consuming alcohol/substances on premises during work hours', 'severity': 'C',
         'description': 'Immediate suspension pending investigation.',
         'default_fine_amount': Decimal('0')},

        # Category D - Terminable Offences (Section 3.5)
        {'name': 'Theft of any kind', 'severity': 'D',
         'description': 'Regardless of value. Immediate termination.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Fraud or financial embezzlement', 'severity': 'D',
         'description': 'Immediate termination.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Willful destruction of company property', 'severity': 'D',
         'description': 'Immediate termination.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Sleeping on duty', 'severity': 'D',
         'description': 'Especially security guards. Immediate termination.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Physical violence or threats against admin/management staff', 'severity': 'D',
         'description': 'Immediate termination.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Three suspensions within 6 months', 'severity': 'D',
         'description': 'Accumulating 3 suspensions within a 6-month period. Immediate termination.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Bringing outside persons to intimidate or threaten', 'severity': 'D',
         'description': 'Cult members, gang associates, family, friends. Immediate termination + law enforcement.',
         'default_fine_amount': Decimal('0')},
        {'name': 'Using cult membership or affiliation to intimidate', 'severity': 'D',
         'description': 'Immediate termination + law enforcement.',
         'default_fine_amount': Decimal('0')},

        # Fine-specific offences (Section 4.1)
        {'name': 'Verbal abuse (worker-to-worker)', 'severity': 'B',
         'description': 'Insults, name-calling, abusive language. 3rd fine = Suspension.',
         'default_fine_amount': Decimal('1500')},
        {'name': 'Threats and intimidation (worker-to-worker)', 'severity': 'B',
         'description': 'Any threat of physical harm related to a work dispute. 3rd fine = Suspension.',
         'default_fine_amount': Decimal('2000')},
        {'name': 'Physical fighting (worker-to-worker)', 'severity': 'C',
         'description': 'Any physical contact with intent to harm. Both parties fined. 3rd fine = Suspension.',
         'default_fine_amount': Decimal('5000')},
        {'name': 'Threats against administrative/management staff', 'severity': 'C',
         'description': 'Fine + Final Written Warning. 2nd threat = Termination.',
         'default_fine_amount': Decimal('5000')},
    ]

    for cat_data in categories:
        OffenceCategory.objects.get_or_create(
            name=cat_data['name'],
            defaults=cat_data
        )


def reverse_seed(apps, schema_editor):
    OffenceCategory = apps.get_model('erp', 'OffenceCategory')
    OffenceCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0057_intercompanyaccount_offencecategory_welfarefund_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_offence_categories, reverse_seed),
    ]