# Generated by Django 6.0 on 2026-04-01 14:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0058_seed_offence_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercompanyaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Starting debt BEFORE using this system. Positive = Block Industry already owes C&C. Negative = C&C owes Block Industry. Enter 0 if starting fresh.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='intercompanyaccount',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-calculated: Opening Balance + Collections − Repayments. Positive = Block Industry owes C&C. Negative = C&C owes Block Industry.', max_digits=14),
        ),
    ]