 # Generated by Django 6.0 on 2026-04-03 08:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0059_intercompanyaccount_opening_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_number', models.PositiveIntegerField(editable=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('BLOCK_SALE', 'Block Sale (Invoice)'), ('QUICK_SALE', 'Quick Sale'), ('SAND_SALE', 'Sand Sale'), ('NON_SALE', 'Non-Sale Item')], default='BLOCK_SALE', max_length=15)),
                ('item_description', models.CharField(help_text='Auto-filled from linked sale, or enter manually for non-sale items', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of items leaving (blocks, bags, pieces, etc.)')),
                ('unit', models.CharField(choices=[('BLOCKS', 'Blocks'), ('BAGS', 'Bags'), ('LITRES', 'Litres'), ('PIECES', 'Pieces'), ('TRIPS', 'Trips'), ('OTHER', 'Other')], default='BLOCKS', max_length=10)),
                ('receiver_name', models.CharField(help_text='Person carrying/receiving the items (driver name, customer name, etc.)', max_length=100)),
                ('vehicle_description', models.CharField(blank=True, help_text="e.g. 'White Hijet', 'Omaba - 608', 'Customer Hilux - ABJ-234'", max_length=150)),
                ('is_verified', models.BooleanField(default=False, help_text='Security guard confirms items match gate log')),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_override', models.BooleanField(default=False, editable=False, help_text='True if this log was created despite exceeding invoice quantity')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(help_text='Staff who authorized this dispatch (auto-set to logged-in user)', on_delete=django.db.models.deletion.PROTECT, related_name='gate_logs_authorized', to=settings.AUTH_USER_MODEL)),
                ('quick_sale', models.ForeignKey(blank=True, help_text='Link to quick sale', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_logs', to='erp.quicksale')),
                ('recorded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sand_sale', models.ForeignKey(blank=True, help_text='Link to sand sale', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_logs', to='erp.sandsale')),
                ('supply_log', models.ForeignKey(blank=True, help_text='Link to block sale invoice (SupplyLog)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_logs', to='erp.supplylog')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Security guard who verified at the gate', limit_choices_to={'role': 'SECURITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_verifications', to='erp.employee')),
            ],
            options={
                'verbose_name': 'Gate Log',
                'verbose_name_plural': 'Gate Logs',
                'ordering': ['-date', '-time', '-gate_number'],
            },
        ),
    ]