# Generated by Django 6.0 on 2026-04-05 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0060_gatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='block_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Number of blocks consumed/given out', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='block_type',
            field=models.ForeignKey(blank=True, help_text='If this expense used blocks (e.g. compensation), select here to auto-deduct stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_production_usage', to='erp.blocktype'),
        ),
        migrations.AddField(
            model_name='expense',
            name='material',
            field=models.ForeignKey(blank=True, help_text='If this expense consumed raw materials (cement, sand), select here to auto-deduct stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_production_usage', to='erp.material'),
        ),
        migrations.AddField(
            model_name='expense',
            name='material_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity consumed (bags, trips, etc.)', max_digits=10, null=True),
        ),
    ]
